# Generated by Django 4.2.13 on 2024-06-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogmodelcontrolbridge',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=20, unique=True, verbose_name='Зав. № машины')),
                ('factory_engine', models.CharField(max_length=20, unique=True, verbose_name='Зав. № двигателя')),
                ('factory_transmission', models.CharField(max_length=20, unique=True, verbose_name='Зав. № трансмиссии')),
                ('factory_main_bridge', models.CharField(max_length=20, unique=True, verbose_name='Зав. № ведущего моста')),
                ('factory_control_bridge', models.CharField(max_length=20, unique=True, verbose_name='Зав. № управляемого моста')),
                ('contract', models.TextField(verbose_name='Договор поставки')),
                ('delivery_data', models.DateField(verbose_name='Дата отгрузки')),
                ('consignee', models.TextField(verbose_name='Грузополучатель')),
                ('address', models.TextField(verbose_name='Адрес поставки')),
                ('equipment', models.TextField(null=True, verbose_name='Комплектация')),
                ('client', models.TextField(verbose_name='Клиент')),
                ('control_bridge_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogmodelcontrolbridge', verbose_name='Модель управляемого моста')),
                ('engine_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogmodelengine', verbose_name='Модель двигателя')),
                ('main_bridge_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogmodelmainbridge', verbose_name='Модель ведущего моста')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogservicecompany', verbose_name='Сервисная компания')),
                ('tech_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogmodeltech', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.catalogmodeltransmission', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
